description: This component retrieves the top 50 products from Amazon based on user
  reviews and saves the product names in a spreadsheet. The component takes a product
  name as input, searches for the top 50 products related to the input, and writes
  the product names to a spreadsheet file with the specified output path.
name: AmazonTop50ProductsReview
parameters: {}
